src/recipe_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf  import settings #added for media files
from django.conf.urls.static import static #added for media files
from .views import login_view, logout_view #added for authentication

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('recipes.urls')),
    path('recipes/', include ('recipes.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/recipes/urls.py
from django.urls import path
from .views import home
from .views import RecipeListView
from .views import RecipeDetailView
from .views import records
from .views import add_recipe

app_name = 'recipes'

urlpatterns = [
    path('', home, name='home'),
    path('list/', RecipeListView.as_view(), name='list'),
    path('list/<pk>', RecipeDetailView.as_view(), name='detail'),
    path('search/', records, name='search'),
    path('add/', add_recipe, name='add'),
]

src/recipes/models.py
from django.db import models
from django.shortcuts import reverse

# Create your models here.
class Recipe(models.Model):
    name= models.CharField(max_length=120)
    cooking_time= models.IntegerField(help_text='In minutes')
    ingredients= models.CharField(max_length=400, help_text='Separated by a comma and space')
    description= models.TextField()
    pic= models.ImageField(upload_to='recipes', default='no_picture.jpg')

    def calculate_difficulty(self):
        ingredients = self.ingredients.split(', ')
        if self.cooking_time < 10 and len(ingredients) < 7:
            difficulty = 'Easy'
        elif self.cooking_time < 10 and len(ingredients) >= 7:
            difficulty = 'Medium'
        elif self.cooking_time >= 10 and len(ingredients) < 7:
            difficulty = 'Intermediate'
        elif self.cooking_time >= 10 and len(ingredients) >= 7:
            difficulty = 'Hard'
        return difficulty

    def __str__(self):
        return str(self.name)
    
    def get_absolute_url(self):
        return reverse('recipes:detail', kwargs={'pk':self.pk})

src/users/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfile(models.Model):
    username= models.OneToOneField(User, on_delete=models.CASCADE)
    name= models.CharField(max_length=120)
    pic= models.ImageField(upload_to='users', default='no_picture.png')

    def __str__(self):
        return f"Profile of {self.username.username}"

src/recipes/forms.py
from django import forms
from .models import Recipe

CHART_CHOICES = (
    ('#1', 'Bar chart'),
    ('#2', 'Pie chart'),
    ('#3', 'Line chart'),
)

class RecipesSearchForm(forms.Form):
    recipe_name = forms.CharField(
        label="Recipe Name",
        max_length=100,
        required=False,
    )
    ingredients = forms.CharField(
        label="Ingredients (separated by commas)",
        max_length=100,
        required=False,
    )
    chart_type = forms.ChoiceField(choices=CHART_CHOICES)

class AddRecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['name', 'cooking_time', 'ingredients', 'description', 'pic']

src/recipe_project/views.py
from django.shortcuts import render, redirect  
#Django authentication libraries           
from django.contrib.auth import authenticate, login, logout
#Django Form for authentication
from django.contrib.auth.forms import AuthenticationForm    

#define a function view called login_view that takes a request from user
def login_view(request):
   #initialize:
   #error_message to None                                 
   error_message = None   
   #form object with username and password fields                             
   form = AuthenticationForm()                            


   #when user hits "login" button, then POST request is generated
   if request.method == 'POST':       
       #read the data sent by the form via POST request                   
       form =AuthenticationForm(data=request.POST)

       #check if form is valid
       if form.is_valid():                                
           username=form.cleaned_data.get('username')      #read username
           password = form.cleaned_data.get('password')    #read password

           #use Django authenticate function to validate the user
           user=authenticate(username=username, password=password)
           if user is not None:                    #if user is authenticated
          #then use pre-defined Django function to login
               login(request, user)                
               return redirect('recipes:list') #& send the user to desired page
       else:                                               #in case of error
           error_message ='ooops.. something went wrong'   #print error message

   #prepare data to send from view to template
   context ={                                             
       'form': form,                                 #send the form data
       'error_message': error_message                     #and the error_message
   }
   #load the login page using "context" information
   return render(request, 'auth/login.html', context)

#define a function view called logout_view that takes a request from user
def logout_view(request):                                  
   logout(request)          #the use pre-defined Django function to logout
   return render(request, 'auth/success-logout.html') #after logging out go to login form (or whichever page you want)

src/recipes/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .models import Recipe
from .forms import RecipesSearchForm, AddRecipeForm
import pandas as pd
from .utils import get_chart, get_recipename_from_id
from django.db.models import Q
from django.contrib.auth.decorators import login_required

class RecipeListView(LoginRequiredMixin, ListView):
    model = Recipe
    template_name = 'recipes/main.html'

class RecipeDetailView(LoginRequiredMixin, DetailView):
    model = Recipe
    template_name = 'recipes/detail.html'


def home(request):
    return render(request, 'recipes/recipes_home.html')

def records(request):
    form = RecipesSearchForm(request.POST or None)
    recipe_df = None
    chart = None
    qs = None

    if form.is_valid():
        recipe_name = form.cleaned_data["recipe_name"]
        ingredients = form.cleaned_data["ingredients"]
        chart_type = form.cleaned_data["chart_type"]

        qs = Recipe.objects.all()

        if recipe_name:
            qs = qs.filter(Q(name__icontains=recipe_name))

        if ingredients:
            qs = qs.filter(Q(ingredients__icontains=ingredients))

        if not recipe_name and not ingredients:
            qs = Recipe.objects.all()

        if qs:
            recipe_df = pd.DataFrame(qs.values('id', 'name', 'cooking_time', 'ingredients'))
            chart = get_chart(chart_type, recipe_df, labels=recipe_df['name'].values)
            recipe_df = recipe_df.to_html()

    context = {
        'form': form,
        'recipe_df': recipe_df,
        'chart': chart,
        'qs': qs,
    }

    return render(request, 'recipes/search.html', context)

@login_required
def add_recipe(request):
    add_form = AddRecipeForm(request.POST, request.FILES)

    if request.method == 'POST':
        if add_form.is_valid():
            recipe = Recipe(
                name=add_form.cleaned_data['name'],
                cooking_time=add_form.cleaned_data['cooking_time'],
                ingredients=add_form.cleaned_data['ingredients'],
                description=add_form.cleaned_data['description'],
                pic=add_form.cleaned_data['pic']
            )
            recipe.save()
            return redirect('recipes:list')

    context = {
        'add_form': add_form,
    }

    return render(request, 'recipes/add_recipe.html', context)

src/users/views.py
from django.shortcuts import render

# Create your views here.

src/recipes/templates/recipes/add_recipe.html
{% load static %}
{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>RecipesApp Home</title>
  <link rel="shortcut icon" href="{% static 'recipes/images/favicon-32x32.png' %}" />
  <link href="https://fonts.googleapis.com/css2?family=Sigmar&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
  {% bootstrap_css %}
  <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/add_recipe.css' %}">
</head>

<body>
  <div class="overlay"></div>
  <div class="container">
    {% block content %}
      <h2 class="my-4">Add Recipe</h2>
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form add_form %}
        <button type="submit" class="btn btn-primary mt-3">Add Recipe</button>
      </form>
    {% endblock %}
  </div>

  {% bootstrap_javascript %}
</body>

</html>

src/recipes/templates/recipes/detail.html
{% load static %}
{% load bootstrap5 %}
<!DOCTYPE html>
<html lang="en">

<head>
  <title>RecipeApp: Your Recipes</title>
  <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="shortcut icon" href="{% static 'recipes/images/favicon-32x32.png' %}" />
  {% bootstrap_css %}
  <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/detail.css' %}">
</head>

<body>
  <div class="background-overlay"></div>
  <h3>Details: {{ object.name }}</h3>
  <div class="details_body">
    <a class="btn btn-secondary back-button" href="{% url 'recipes:list' %}">Back</a>
    <div class="food_image_container">
      <img class="food_image" src="{{ object.pic.url }}" alt="{{ object.name }}" />
    </div>
    <b>Name:</b> <span class="object">{{ object.name }}</span> <br>
    <b>Description:</b> <span class="object">{{ object.description }}</span> <br>
    <b>Cooking Time:</b> <span class="object">{{ object.cooking_time }}</span> <br>
    <b>Difficulty:</b> <span class="object">{{ object.calculate_difficulty }}</span> <br>
    <b>Ingredients:</b> <span class="object">{{ object.ingredients }}</span> <br>
  </div>
</body>

</html>

src/recipes/templates/recipes/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <title>RecipeApp: Your Recipes</title>
  <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="shortcut icon" href="{% static 'recipes/images/favicon-32x32.png' %}" />
  <link href="https://fonts.googleapis.com/css2?family=Sigmar&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'recipes/css/main.css' %}">
</head>

<body>
  <div class="container">
    <div class="background-overlay"></div>
    <div class="logo">
      <img src="{% static 'recipes/images/favicon-32x32.png' %}" alt="Logo">
      <span class="logo-text">MyRecipes</span>
      <a class="add" href="{%url 'recipes:add' %}">AddRecipe</a>
    </div>

    <a class="search" href="{%url 'recipes:search' %}">Search</a>
    <a href ="{%url 'logout' %}" class="logout"> Logout </a>
    <h1>MyRecipes</h1>
    <ul class="recipe-list">
      {% for object in object_list %}
      <li class="recipe-item">
        <a href="{{ object.get_absolute_url }}">
          <div class="recipe-image-container">
            <img class="recipe-image" src="{{ object.pic.url }}" alt="{{ object.name }}" />
            <div class="recipe-title-overlay">{{ object.name }}</div>
          </div>
        </a>
      </li>
      {% endfor %}
    </ul>
  </div>
</body>

</html>

src/recipes/templates/recipes/recipes_home.html
{% load static %}
{% load bootstrap5 %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>RecipesApp Home</title>
  <link rel="shortcut icon" href="{% static 'recipes/images/favicon-32x32.png' %}" />
  <link href="https://fonts.googleapis.com/css2?family=Sigmar&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
  {% bootstrap_css %}
  {% bootstrap_javascript %}
  <link rel="stylesheet" type="text/css" href="{% static 'recipes/css/recipes_home.css' %}">
</head>

<body>
  <div class="overlay"></div>
  <div class="logo">
    <img src="{% static 'recipes/images/favicon-32x32.png' %}" alt="Logo">
    <span class="logo-text">MyRecipes</span>
  </div>
  <div class="container login-container">
    <h1><span class="text-font">Welcome to</span> <span class="myrecipetext">MyRecipesApp</span></h1>
    <a href="{% url 'login' %}" class="my-login-button">Login</a>
    <div class="slogan">
      <h3>Find Happiness In Cooking</h3>
    </div>
  </div>

    <!-- Footer -->
    <footer class="page-footer">
      <p class="page-footer__item">Find me on:</p>
      <div class="social-media page-footer__item">
        <!-- Github logo -->
        <a href="https://github.com/OBo1307/" target="_blank"><img src="{% static 'recipes/images/github.png' %}"
            alt="Github"></a>
        <!-- Personal Portofolio logo -->
        <a href="https://www.bogdano.tech/" target="_blank"><img src="{% static 'recipes/images/techb.png' %}"
            alt="Twitter"></a>
        <!-- LinkedIN logo -->
        <a href="https://www.linkedin.com/in/bogdan-ionut-ochrim-6887ab267/" target="_blank"><img
            src="{% static 'recipes/images/linkedin.png' %}" alt="LinkedIn"></a>
      </div>
    </footer>
    
</body>

</html>

src/recipes/templates/recipes/search.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <title>RecipeApp: Search</title>
  <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1" />
  <link rel="shortcut icon" href="{% static 'recipes/images/favicon-32x32.png' %}" />
  <link href="https://fonts.googleapis.com/css2?family=Sigmar&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'recipes/css/search.css' %}">
</head>

<body>
  <div class="background-overlay"></div>
  <div class="logo">
    <img src="{% static 'recipes/images/favicon-32x32.png' %}" alt="Logo">
    <span class="logo-text">MyRecipes</span>
  </div>
  <a href="{% url 'recipes:list' %}" class="back-btn">Back</a>
  <a href="{% url 'logout' %}" class="logout">Logout</a>

  <div class="search_results">
    <h1>Search for recipes</h1>

    <form action="" method="POST">
      {% csrf_token %}
      {{ form }}
      <button type="submit">Search</button>
    </form>

    <br>
    {% if qs %}
    <table>
      <tr>
        <th>Name</th>
        <th>Ingredients</th>
        <th>Cooking Time (minutes)</th>
      </tr>
      {% for recipe in qs %}
      <tr>
        <td><a href="{{ recipe.get_absolute_url }}">{{ recipe.name }}</a></td>
        <td>{{ recipe.ingredients }}</td>
        <td>{{ recipe.cooking_time }}</td>
      </tr>
      {% endfor %}
    </table>
    <br>
    <img src="data:image/png;base64, {{ chart|safe }}">
    {% else %}
    <h3>No data, try again.</h3>
    {% endif %}
  </div>
</body>

</html>